language: java
jdk: oraclejdk8
sudo: required
services:
  - docker
env:
  global:
    secure: o2dQQRfJiO5fXV0cP28ZQGG6iJGpFlJuiDlJtufqWtPD3noj3VK+aIUQvT4zOK81QpiJGBNrR+6lfQhooZZluJ0ZpG/dAURzq2GqdxRfQEAxCqI2TiIOwCdT/Bl2wXXu5YyaKNPboi3UiMebD/K9zDzbJ1wYBkFHC9DDCDwjdsIq2UAtx/Ou3CilnxMrEeMWwgOgcQfGAJs1QxBy8VNFWmTsIcEO+dI5d9vUjcxDQ3D7PPg5D5pnX4bY3E/XwHlTbALTcWl//kW/yS1+5r/61Js9wINJzr5hzAe1bEmwjCm3yYWbEW0sFKeBspqMh/YDb26qlJdUgmjzdkJ0DCZiIyyKEf0akL5OJsLQhUaR9/NGDCLjR9bwwVvc1SZkYkaj/2+n78vQZk+cF/x/6Cv/yWfAfhHgHMAMbl8bTxWhrclx5/Fh7exoBm/NN81f509+Yht+I9fK3n7ngUrJTYf6u51+obhhaLya//7Td1x/O6iRXND0JwvtTOmsTKt8aUbhG3LtsQxKx6Pb7HV1394eGseykadomESbyoA2j/jXHcPrWLHhKuoqrBJljquJQrR3pc2z+8H/t+DMuqBg2YLwu9yeT0fM7vwlrs8xxNTRWrCZ8kRgF7GfBNNmlp/Uc8iEmQypK3Pw+TDcRxNkoZPNptSHXSWyKYhdWMLVUKtjk78=
after_success:
  - ./.travis/create_branch.sh
